/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as DocsRouteImport } from "./routes/docs"
import { Route as PlaygroundRouteImport } from "./routes/playground"
import { Route as DocsCoreRouteImport } from "./routes/docs.core"
import { Route as DocsInstallationRouteImport } from "./routes/docs.installation"
import { Route as ExtensionsIndexRouteImport } from "./routes/extensions.index"
import { Route as ExtensionsIdRouteImport } from "./routes/extensions.$id"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: "/playground",
  path: "/playground",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCoreRoute = DocsCoreRouteImport.update({
  id: "/core",
  path: "/core",
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: "/installation",
  path: "/installation",
  getParentRoute: () => DocsRoute,
} as any)
const ExtensionsIndexRoute = ExtensionsIndexRouteImport.update({
  id: "/extensions/",
  path: "/extensions/",
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsIdRoute = ExtensionsIdRouteImport.update({
  id: "/extensions/$id",
  path: "/extensions/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/docs": typeof DocsRouteWithChildren
  "/playground": typeof PlaygroundRoute
  "/docs/core": typeof DocsCoreRoute
  "/docs/installation": typeof DocsInstallationRoute
  "/extensions/$id": typeof ExtensionsIdRoute
  "/extensions/": typeof ExtensionsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/docs": typeof DocsRouteWithChildren
  "/playground": typeof PlaygroundRoute
  "/docs/core": typeof DocsCoreRoute
  "/docs/installation": typeof DocsInstallationRoute
  "/extensions/$id": typeof ExtensionsIdRoute
  "/extensions": typeof ExtensionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/docs": typeof DocsRouteWithChildren
  "/playground": typeof PlaygroundRoute
  "/docs/core": typeof DocsCoreRoute
  "/docs/installation": typeof DocsInstallationRoute
  "/extensions/$id": typeof ExtensionsIdRoute
  "/extensions/": typeof ExtensionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/docs"
    | "/playground"
    | "/docs/core"
    | "/docs/installation"
    | "/extensions/$id"
    | "/extensions/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/docs"
    | "/playground"
    | "/docs/core"
    | "/docs/installation"
    | "/extensions/$id"
    | "/extensions"
  id:
    | "__root__"
    | "/"
    | "/docs"
    | "/playground"
    | "/docs/core"
    | "/docs/installation"
    | "/extensions/$id"
    | "/extensions/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
  ExtensionsIdRoute: typeof ExtensionsIdRoute
  ExtensionsIndexRoute: typeof ExtensionsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs": {
      id: "/docs"
      path: "/docs"
      fullPath: "/docs"
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/playground": {
      id: "/playground"
      path: "/playground"
      fullPath: "/playground"
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/core": {
      id: "/docs/core"
      path: "/core"
      fullPath: "/docs/core"
      preLoaderRoute: typeof DocsCoreRouteImport
      parentRoute: typeof DocsRoute
    }
    "/docs/installation": {
      id: "/docs/installation"
      path: "/installation"
      fullPath: "/docs/installation"
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    "/extensions/": {
      id: "/extensions/"
      path: "/extensions"
      fullPath: "/extensions/"
      preLoaderRoute: typeof ExtensionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/extensions/$id": {
      id: "/extensions/$id"
      path: "/extensions/$id"
      fullPath: "/extensions/$id"
      preLoaderRoute: typeof ExtensionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsCoreRoute: typeof DocsCoreRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCoreRoute: DocsCoreRoute,
  DocsInstallationRoute: DocsInstallationRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
  ExtensionsIdRoute: ExtensionsIdRoute,
  ExtensionsIndexRoute: ExtensionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
